### PR TITLE
support ghc-8.4

### PR DESCRIPTION
**Pull request by soenkehahn**

### CODE REVIEW

**Comment by soenkehahn** [comment]
@harendra-kumar: Thanks for reporting this. Could you confirm that this fixes #56 for you? If you do, I'll make a release to hackage.

I'd also appreciate a review, if you're up for that. Some comments:

- I've removed the `Monoid` instance, since that was the easiest way to support all compilers (`7.8` - `8.4`). (Another option would've been to depend on `semigroup` which works on all those compiler versions, but that would mean to add the transitive dependency of `text` without actually using that package. Which sounds like a bad idea.)
- The `Flag` type is internal, so removing the instance shouldn't matter to library users.
- This would only require a patch-level version bump. (Especially here I'd appreciate a second opinion.)

**Comment by harendra-kumar** [comment]
I took a look at the changes. Looks good to me. There is no user visible impact so patch level bump should be fine. Let me try this on my repo.

**Comment by harendra-kumar** [comment]
It worked for me! Thanks! Please upload to hackage.

**Comment by soenkehahn** [comment]
Released as `0.13.0.2`. Thanks a lot for the review, @harendra-kumar!

**Comment by harendra-kumar** [comment]
@soenkehahn thanks for writing and maintaining this cool package!

**Pull request merged**
