### PR TITLE
Replace some code with generics-sop library functions.

### PR DESCRIPTION
**Pull request by kosmikus**
Great to see more packages that use `generics-sop`!

On a quick scan, I found that you essentially reimplemented some functions that are directly provided by `generics-sop`. This PR modifies your code such that you actually use them. Of course, it's a purely stylistic PR that adds no new functionality, so feel free to reject it. I'd also be interested to learn how we could improve documentation so that you might have found the functions when you needed them.

### CODE REVIEW

**Comment by soenkehahn** [comment]
@kosmikus: Thanks! I suspected that you would be able to come up with a PR like this. :)

If you find the time you could also look at `mapFieldInfoM`: https://github.com/zalora/getopt-generics/blob/master/src/System/Console/GetOpt/Generics/Internal.hs#L23. Especially the duplication of `mapConsInfo` and `mapFieldInfo` (in the `where`-clause) seems very redundant. But I couldn't figure out how to make it typecheck without.

**Comment by soenkehahn** [comment]
Regarding the documentation in `generics-sop`: I think the biggest problem is that I had to wrap my head around the basic concepts and I find that much easier to do when refraining from using higher-level convenience combinators. But here's some feedback about the documentation/library:
- I think the function names are in part not self-explanatory. For example I still wonder what the `h` in e.g. `hliftA` stands for.
- Generally I don't like abbreviations that much: `apInjs_NP` sounds much more intimidating than `applyInjections_NP`. And personally I don't mind typing the additional characters.
- I find libraries more accessible that very clearly separate the core of the library from things that are provided on top of that and implemented in terms of the core. In `generics-sop` it is not very apparent to newcomers that e.g. `HCollapse` is not essential to the library whereas `NS` is. I would separate them by module. (I admit that this may not increase the usage of things like `hliftA` since they would be in a separate module but I think it would help people to understand the big picture faster.)

Well, I'm not too sure how useful my comments are.

Generally `generics-sop` is pretty awesome. Thanks for working on it!

**Comment by kosmikus** [comment]
Thanks for the feedback.
- I'm not completely happy with the naming scheme in `generics-sop` myself, but I don't really want to make breaking name changes unless I have a consistent story for the whole library that I believe to be a substantial improvement.
- The 'h' is indeed unexplained. I personally think it's for "higher-order/kinded", but I'm not actually sure. Edsko may have a different expansion in mind. Are you sure that just the different names would have helped here, though? I mean, I can completely understand a personal dislike for a name such as `hliftA` or `apInjs_NP`, but does it make a difference between the function being found or overlooked?
- I don't think I agree about separating things into different modules. What's "essential" is relative. I think it's perhaps not essential, but important that the library comes with a range of powerful combinators. If you reduce it to just the bare-bones definitions of `NP` and `NS`, then it's still useful, but there's not a significant difference to other generic programming libraries then. Also, it's typical to distribute a library that combines datatypes with common functions on that datatype, isn't it?

**Comment by soenkehahn** [comment]
Regarding the second bullet point: Of course I can only speak for myself, but yes, I think for me it would make a difference. (For example I looked at your second PR (#26) and wondered what `Comp` means. I suspected `Compare`. It would have been easier if it was just called `Compose`.)

Regarding the third one: Yes, you're right. What I meant to say is that it's easier to learn a library when it's clear what parts are the core (that need to be understood) and what's implemented on top for convenience (and can safely be ignored in the beginning and explored later). For example it's probably not useful to look at `HCollapse` before understanding how `NS`, `NP` and `from` and `to` work.
But I agree that putting them in different modules wouldn't be a good idea. But it could be made more clear in the haddock docs structure what's what.

**Pull request merged**
